### ISSUE TITLE
cannot compile due to No such var: p/min

### ISSUE THREAD

**Issue by zcaudate** [ztellman/byte-streams#33]
I'm not sure why this is happening but I'm getting this when using the CI pipeline on Gitlab.

the versions are byte-streams 0.2.0 and primitive-math 0.1.4

Exception in thread "main" java.lang.RuntimeException: No such var: p/min, compiling:(byte_streams/pushback_stream.clj:37:38)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3766)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1009)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)

**Comment by ztellman** [comment]
Those are some pretty old versions of the libraries, can you try targeting `[byte-streams "0.2.3"]`?

**Comment by zcaudate** [comment]
I tried that. It only fails on CI and I'm not sure why.

I'm playing around with [clojurecl](https://github.com/uncomplicate/clojurecl/issues/16) which is depending on [vertigo](https://github.com/ztellman/vertigo/blob/master/project.clj) and it's still using on `"0.1.4"`. I'll set up the [repo](https://github.com/zcaudate-me/image-bench) with travis to try and reproduce it within the next couple of days.

**Comment by ztellman** [comment]
Can you share the output of ‘lein deps :tree’?

**Comment by zcaudate** [comment]
```
chris on chapterhouse in image-bench using ± master +
08:27:25 λ  lein trampoline deps :tree
Possibly confusing dependencies found:
[org.clojure/clojure "1.8.0"]
 overrides
[uncomplicate/clojurecl "0.8.0"] -> [uncomplicate/commons "0.4.0"] -> [org.clojure/clojure "1.9.0"]
 and
[uncomplicate/clojurecl "0.8.0"] -> [org.clojure/clojure "1.9.0"]

Consider using these exclusions:
[uncomplicate/clojurecl "0.8.0" :exclusions [org.clojure/clojure]]

[org.ow2.asm/asm "5.1"]
 overrides
[zcaudate/lucid.unit "1.4.0"] -> [zcaudate/lucid.core.code "1.4.0"] -> [zcaudate/lucid.query "1.4.0"] -> [zcaudate/lucid.legacy "1.4.0"] -> [org.ow2.asm/asm "6.0"]
 and
[zcaudate/lucid.publish "1.4.0"] -> [zcaudate/lucid.core.code "1.4.0"] -> [zcaudate/lucid.query "1.4.0"] -> [zcaudate/lucid.legacy "1.4.0"] -> [org.ow2.asm/asm "6.0"]
 and
[zcaudate/lucid.unit "1.4.0"] -> [zcaudate/lucid.query "1.4.0"] -> [zcaudate/lucid.legacy "1.4.0"] -> [org.ow2.asm/asm "6.0"]
 and
[zcaudate/lucid.publish "1.4.0"] -> [zcaudate/lucid.query "1.4.0"] -> [zcaudate/lucid.legacy "1.4.0"] -> [org.ow2.asm/asm "6.0"]

Consider using these exclusions:
[zcaudate/lucid.unit "1.4.0" :exclusions [org.ow2.asm/asm]]
[zcaudate/lucid.publish "1.4.0" :exclusions [org.ow2.asm/asm]]

[org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]
 overrides
[cider/cider-nrepl "0.15.1"] -> [org.clojure/tools.nrepl "0.2.13" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[cider/cider-nrepl "0.15.1" :exclusions [org.clojure/tools.nrepl]]

[zcaudate/lucid.publish "1.4.0"] -> [rewrite-clj "0.6.0"] -> [org.clojure/tools.reader "0.10.0" :exclusions [org.clojure/clojure]]
 overrides
[uncomplicate/clojurecl "0.8.0"] -> [org.clojure/core.async "0.4.474"] -> [org.clojure/tools.analyzer.jvm "0.7.0"] -> [org.clojure/tools.reader "1.0.0-beta4"]

Consider using these exclusions:
[uncomplicate/clojurecl "0.8.0" :exclusions [org.clojure/tools.reader]]

 [cider/cider-nrepl "0.15.1"]
   [org.tcrawley/dynapath "0.2.5" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [com.twelvemonkeys.imageio/imageio-tiff "3.3.2"]
   [com.twelvemonkeys.common/common-image "3.3.2"]
   [com.twelvemonkeys.common/common-io "3.3.2"]
   [com.twelvemonkeys.common/common-lang "3.3.2"]
   [com.twelvemonkeys.imageio/imageio-core "3.3.2"]
   [com.twelvemonkeys.imageio/imageio-metadata "3.3.2"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/tools.namespace "0.2.11"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [org.ow2.asm/asm "5.1"]
 [uncomplicate/clojurecl "0.8.0"]
   [org.clojure/core.async "0.4.474"]
     [org.clojure/tools.analyzer.jvm "0.7.0"]
       [org.clojure/core.memoize "0.5.9"]
         [org.clojure/core.cache "0.6.5"]
           [org.clojure/data.priority-map "0.0.7"]
       [org.clojure/tools.analyzer "0.6.9"]
       [org.ow2.asm/asm-all "4.2"]
   [org.jocl/jocl "2.0.0"]
   [uncomplicate/commons "0.4.0"]
   [vertigo "0.1.4"]
     [byte-streams "0.2.0"]
       [manifold "0.1.0"]
         [org.clojure/tools.logging "0.3.1"]
     [clj-tuple "0.2.2"]
     [potemkin "0.4.2"]
       [riddley "0.1.11"]
     [primitive-math "0.1.4"]
 [virgil "0.1.7"]
 [zcaudate/hara.object "2.8.1" :scope "test"]
   [zcaudate/hara.class.enum "2.8.1" :scope "test"]
   [zcaudate/hara.data.map "2.8.1" :scope "test"]
   [zcaudate/hara.protocol.map "2.8.1" :scope "test"]
   [zcaudate/hara.protocol.object "2.8.1" :scope "test"]
   [zcaudate/hara.protocol.string "2.8.1" :scope "test"]
 [zcaudate/hara.test "2.8.1" :scope "test"]
   [zcaudate/hara.common.checks "2.8.1" :scope "test"]
   [zcaudate/hara.common.primitives "2.8.1" :scope "test"]
     [zcaudate/hara.common.error "2.8.1" :scope "test"]
   [zcaudate/hara.event "2.8.1" :scope "test"]
     [zcaudate/hara.data.seq "2.8.1" :scope "test"]
   [zcaudate/hara.io.ansii "2.8.1" :scope "test"]
   [zcaudate/hara.io.project "2.8.1" :scope "test"]
   [zcaudate/hara.namespace.import "2.8.1" :scope "test"]
 [zcaudate/lucid.core.inject "1.4.0" :scope "test"]
 [zcaudate/lucid.mind "1.4.0" :scope "test"]
 [zcaudate/lucid.package "1.4.0" :scope "test"]
   [org.bouncycastle/bcpg-jdk15on "1.58" :scope "test"]
   [org.bouncycastle/bcprov-jdk15on "1.58" :scope "test"]
   [zcaudate/hara.io.archive "2.8.1" :scope "test"]
     [zcaudate/hara.protocol.archive "2.8.1" :scope "test"]
   [zcaudate/hara.io.classpath "2.8.1" :scope "test"]
     [zcaudate/hara.class.multi "2.8.1" :scope "test"]
     [zcaudate/hara.io.classloader "2.8.1" :scope "test"]
   [zcaudate/hara.io.encode "2.8.1" :scope "test"]
   [zcaudate/hara.reflect "2.8.1" :scope "test"]
     [zcaudate/hara.class.inheritance "2.8.1" :scope "test"]
     [zcaudate/hara.common "2.8.1" :scope "test"]
       [zcaudate/hara.common.hash "2.8.1" :scope "test"]
       [zcaudate/hara.common.state "2.8.1" :scope "test"]
         [zcaudate/hara.protocol.state "2.8.1" :scope "test"]
       [zcaudate/hara.common.watch "2.8.1" :scope "test"]
         [zcaudate/hara.function.args "2.8.1" :scope "test"]
   [zcaudate/hara.security "2.8.1" :scope "test"]
   [zcaudate/lucid.aether "1.4.0" :scope "test"]
     [org.apache.maven/maven-aether-provider "3.3.9" :scope "test"]
       [org.apache.commons/commons-lang3 "3.4" :scope "test"]
       [org.apache.maven/maven-model-builder "3.3.9" :scope "test"]
         [com.google.guava/guava "18.0" :scope "test"]
         [org.apache.maven/maven-artifact "3.3.9" :scope "test"]
         [org.apache.maven/maven-builder-support "3.3.9" :scope "test"]
         [org.codehaus.plexus/plexus-interpolation "1.21" :scope "test"]
       [org.apache.maven/maven-model "3.3.9" :scope "test"]
       [org.apache.maven/maven-repository-metadata "3.3.9" :scope "test"]
       [org.codehaus.plexus/plexus-component-annotations "1.6" :scope "test" :exclusions [[junit]]]
       [org.codehaus.plexus/plexus-utils "3.0.22" :scope "test"]
       [org.eclipse.aether/aether-impl "1.0.2.v20150114" :scope "test"]
     [org.eclipse.aether/aether-api "1.1.0" :scope "test"]
     [org.eclipse.aether/aether-connector-basic "1.1.0" :scope "test"]
     [org.eclipse.aether/aether-spi "1.1.0" :scope "test"]
     [org.eclipse.aether/aether-transport-file "1.1.0" :scope "test"]
     [org.eclipse.aether/aether-transport-http "1.1.0" :scope "test"]
       [org.apache.httpcomponents/httpclient "4.3.5" :scope "test" :exclusions [[commons-logging]]]
         [commons-codec "1.6" :scope "test"]
         [org.apache.httpcomponents/httpcore "4.3.2" :scope "test"]
       [org.slf4j/jcl-over-slf4j "1.6.2" :scope "test"]
         [org.slf4j/slf4j-api "1.6.2" :scope "test"]
     [org.eclipse.aether/aether-util "1.1.0" :scope "test"]
 [zcaudate/lucid.publish "1.4.0" :scope "test"]
   [hiccup "1.0.5" :scope "test"]
   [markdown-clj "1.0.1" :scope "test"]
   [rewrite-clj "0.6.0" :scope "test"]
     [org.clojure/tools.reader "0.10.0" :exclusions [[org.clojure/clojure]]]
   [zcaudate/hara.data.nested "2.8.1" :scope "test"]
     [zcaudate/hara.expression.shorthand "2.8.1" :scope "test"]
       [zcaudate/hara.function.dispatch "2.8.1" :scope "test"]
       [zcaudate/hara.namespace.resolve "2.8.1" :scope "test"]
   [zcaudate/hara.io.file "2.8.1" :scope "test"]
   [zcaudate/hara.io.watch "2.8.1" :scope "test"]
     [zcaudate/hara.protocol.watch "2.8.1" :scope "test"]
   [zcaudate/hara.string.case "2.8.1" :scope "test"]
     [zcaudate/hara.common.string "2.8.1" :scope "test"]
   [zcaudate/hara.string.mustache "2.8.1" :scope "test"]
     [zcaudate/hara.data.path "2.8.1" :scope "test"]
     [zcaudate/hara.string.path "2.8.1" :scope "test"]
   [zcaudate/hara.string.prose "2.8.1" :scope "test"]
   [zcaudate/lucid.core.code "1.4.0" :scope "test"]
   [zcaudate/lucid.query "1.4.0" :scope "test"]
     [zcaudate/lucid.legacy "1.4.0" :scope "test"]
 [zcaudate/lucid.unit "1.4.0" :scope "test"]
```

**Comment by zcaudate** [comment]
I noticed that it has something to do with lein-vigil. If I disable it, it's fine but when I enable it, I get
```
chris on chapterhouse in image-bench using ± master
08:25:33 λ  lein trampoline test


---- Project (image-bench:1) ----

image-bench.sobel-test

recompiling all files in ["/Users/chris/Development/chit/image-bench/source/java"]
:reloading (image-bench.image image-bench.grayscale image-bench.sobel image-bench.sobel-test image-bench.calibration)
:error-while-loading image-bench.grayscale
Exception in thread "main" java.lang.Exception: namespace 'manifold.utils' not found, compiling:(manifold/deferred.clj:1:1)
	at clojure.core$throw_if.invokeStatic(core.clj:5656)
	at clojure.core$load_lib.invokeStatic(core.clj:5742)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5778)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at manifold.deferred$eval16471$loading__5569__auto____16472.invoke(deferred.clj:1)
	at manifold.deferred$eval16471.invokeStatic(deferred.clj:1)
	at manifold.deferred$eval16471.invoke(deferred.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at manifold.stream$eval16463$loading__5569__auto____16464.invoke(stream.clj:1)
	at manifold.stream$eval16463.invokeStatic(stream.clj:1)
	at manifold.stream$eval16463.invoke(stream.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5778)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at byte_streams$eval16455$loading__5569__auto____16456.invoke(byte_streams.clj:1)
	at byte_streams$eval16455.invokeStatic(byte_streams.clj:1)
	at byte_streams$eval16455.invoke(byte_streams.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at vertigo.bytes$eval15478$loading__5569__auto____15479.invoke(bytes.clj:1)
	at vertigo.bytes$eval15478.invokeStatic(bytes.clj:1)
	at vertigo.bytes$eval15478.invoke(bytes.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5778)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at uncomplicate.clojurecl.info$eval15472$loading__5569__auto____15473.invoke(info.clj:9)
	at uncomplicate.clojurecl.info$eval15472.invokeStatic(info.clj:9)
	at uncomplicate.clojurecl.info$eval15472.invoke(info.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5778)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at uncomplicate.clojurecl.core$eval15208$loading__5569__auto____15209.invoke(core.clj:9)
	at uncomplicate.clojurecl.core$eval15208.invokeStatic(core.clj:9)
	at uncomplicate.clojurecl.core$eval15208.invoke(core.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at image_bench.sobel$eval15200$loading__5569__auto____15201.invoke(sobel.clj:1)
	at image_bench.sobel$eval15200.invokeStatic(sobel.clj:1)
	at image_bench.sobel$eval15200.invoke(sobel.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at image_bench.sobel_test$eval15194$loading__5569__auto____15195.invoke(sobel_test.clj:1)
	at image_bench.sobel_test$eval15194.invokeStatic(sobel_test.clj:1)
	at image_bench.sobel_test$eval15194.invoke(sobel_test.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.lang.RT$3.invoke(RT.java:320)
	at hara.test.runner$run$fn__1656$fn__1665.invoke(runner.clj:149)
	at hara.test.runner$run$fn__1656.invoke(runner.clj:148)
	at hara.test.runner$accumulate$fn__1619.invoke(runner.clj:23)
	at hara.test.runner$accumulate.invokeStatic(runner.clj:22)
	at hara.test.runner$accumulate.invoke(runner.clj:12)
	at hara.test.runner$run.invokeStatic(runner.clj:145)
	at hara.test.runner$run.invoke(runner.clj:94)
	at hara.test.runner$run.invokeStatic(runner.clj:132)
	at hara.test.runner$run.invoke(runner.clj:94)
	at hara.test.runner$run.invokeStatic(runner.clj:130)
	at hara.test.runner$run.invoke(runner.clj:94)
	at hara.test$_main.invokeStatic(test.clj:83)
	at hara.test$_main.doInvoke(test.clj:78)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at user$eval15179.invokeStatic(form-init1526292321474187801.clj:1)
	at user$eval15179.invoke(form-init1526292321474187801.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: namespace 'manifold.utils' not found
	... 246 more
```

**Comment by zcaudate** [comment]
the project is here: https://github.com/zcaudate-me/image-bench

**Comment by ztellman** [comment]
Okay, I've also had intermittent issues with `lein-virgil` causing tests to fail, I'm going to look into trying to make sure it doesn't try to recompile during tests.

**Comment by zcaudate** [comment]
@ztellman: thanks. that'll be awesome.

**Comment by zcaudate** [comment]
@ztellman: thanks. that'll be awesome.
